/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Main.Member;

/**
 *
 * @author Claire's pc
 */
public class AddPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddPage.class.getName());

    /**
     * Creates new form AddPage
     */
    public AddPage() {
        initComponents();
        
   
        
        tblMembersList.setVisible(false);
        lblFirstname.setVisible(false);
        txtFirstname.setVisible(false);
        lblSurname.setVisible(false);
        txtSurname.setVisible(false);
        lblGender.setVisible(false);
        radioMale.setVisible(false);
        radioFemale.setVisible(false);
        lblDob.setVisible(false);
        txtDob.setVisible(false);
        lblMemberID.setVisible(false);
        txtMemberID.setVisible(false);
        lblPhone.setVisible(false);
        txtPhone.setVisible(false);
        lblAddress.setVisible(false);
        txtAddress.setVisible(false);
        lblType.setVisible(false);
        radioStaff.setVisible(false);
        radioStudent.setVisible(false);
        lblType.setVisible(false);
        lblPosition.setVisible(false);
        txtPosition.setVisible(false);
        lblDepartment.setVisible(false);
        txtDepartment.setVisible(false);
        lblCourse.setVisible(false);
        txtCourse.setVisible(false);
        lblTeam.setVisible(false);
        txtTeam.setVisible(false);
        lblEmployeeID.setVisible(false);
        txtEmployeeID.setVisible(false);
        lblTrainer.setVisible(false);
        btnYes.setVisible(false);
        btnNo.setVisible(false);
        lblMembersList.setVisible(false);
        tblMembersList.setVisible(false);
        jScrollPane1.setVisible(false);
        lblSalary.setVisible(false);
        txtSalary.setVisible(false);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseTypeRadioGroup = new javax.swing.ButtonGroup();
        genderRadioGroup = new javax.swing.ButtonGroup();
        typeRadioGroup = new javax.swing.ButtonGroup();
        yesOrNORadioGroup = new javax.swing.ButtonGroup();
        lblChooseType = new javax.swing.JLabel();
        radioEmployee = new javax.swing.JRadioButton();
        radioMember = new javax.swing.JRadioButton();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        lblSurname = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblMemberID = new javax.swing.JLabel();
        txtMemberID = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        lblDob = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblType = new javax.swing.JLabel();
        radioStaff = new javax.swing.JRadioButton();
        radioStudent = new javax.swing.JRadioButton();
        lblPosition = new javax.swing.JLabel();
        txtPosition = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        lblCourse = new javax.swing.JLabel();
        txtCourse = new javax.swing.JTextField();
        lblTeam = new javax.swing.JLabel();
        txtTeam = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        lblTrainer = new javax.swing.JLabel();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        lblMembersList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembersList = new javax.swing.JTable();
        lblSalary = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblChooseType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblChooseType.setForeground(new java.awt.Color(0, 0, 153));
        lblChooseType.setText("Choose type : ");

        chooseTypeRadioGroup.add(radioEmployee);
        radioEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioEmployee.setText("Employee");
        radioEmployee.addActionListener(this::radioEmployeeActionPerformed);

        chooseTypeRadioGroup.add(radioMember);
        radioMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioMember.setText("Member");
        radioMember.addActionListener(this::radioMemberActionPerformed);

        lblFirstname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(0, 0, 153));
        lblFirstname.setText("First Name :");

        txtFirstname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFirstname.addActionListener(this::txtFirstnameActionPerformed);

        lblSurname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSurname.setForeground(new java.awt.Color(0, 0, 153));
        lblSurname.setText("Surname : ");

        txtSurname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSurname.addActionListener(this::txtSurnameActionPerformed);

        lblMemberID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMemberID.setForeground(new java.awt.Color(0, 0, 153));
        lblMemberID.setText("Member ID :");

        txtMemberID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMemberID.addActionListener(this::txtMemberIDActionPerformed);

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 0, 153));
        lblGender.setText("Gender :");

        genderRadioGroup.add(radioMale);
        radioMale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioMale.setText("Male");

        genderRadioGroup.add(radioFemale);
        radioFemale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioFemale.setText("Female");

        lblDob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDob.setForeground(new java.awt.Color(0, 0, 153));
        lblDob.setText("DOB :");

        txtDob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDob.setText("DD/MM/YYY");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(0, 0, 153));
        lblPhone.setText("Phone no :");

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhone.addActionListener(this::txtPhoneActionPerformed);

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(0, 0, 153));
        lblAddress.setText("Address :");

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAddress.setText("Bld/Hs no, Road no, Block no");
        txtAddress.addActionListener(this::txtAddressActionPerformed);

        lblType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblType.setForeground(new java.awt.Color(0, 0, 153));
        lblType.setText("Type :");

        typeRadioGroup.add(radioStaff);
        radioStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioStaff.setText("Staff");
        radioStaff.addActionListener(this::radioStaffActionPerformed);

        typeRadioGroup.add(radioStudent);
        radioStudent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioStudent.setText("Student");
        radioStudent.addActionListener(this::radioStudentActionPerformed);

        lblPosition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(0, 0, 153));
        lblPosition.setText("Position :");

        txtPosition.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPosition.addActionListener(this::txtPositionActionPerformed);

        lblDepartment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(0, 0, 153));
        lblDepartment.setText("Department :");

        txtDepartment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDepartment.addActionListener(this::txtDepartmentActionPerformed);

        lblCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(0, 0, 153));
        lblCourse.setText("Course :");

        txtCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCourse.addActionListener(this::txtCourseActionPerformed);

        lblTeam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTeam.setForeground(new java.awt.Color(0, 0, 153));
        lblTeam.setText("Team :");

        txtTeam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTeam.addActionListener(this::txtTeamActionPerformed);

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 0, 153));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 0, 153));
        btnSave.setText("save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        lblEmployeeID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmployeeID.setForeground(new java.awt.Color(0, 0, 153));
        lblEmployeeID.setText("Employee ID :");

        txtEmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTrainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTrainer.setForeground(new java.awt.Color(0, 0, 153));
        lblTrainer.setText("Trainer :");

        yesOrNORadioGroup.add(btnYes);
        btnYes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnYes.setText("Yes");
        btnYes.addActionListener(this::btnYesActionPerformed);

        yesOrNORadioGroup.add(btnNo);
        btnNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNo.setText("No");
        btnNo.addActionListener(this::btnNoActionPerformed);

        lblMembersList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMembersList.setForeground(new java.awt.Color(0, 0, 153));
        lblMembersList.setText("Members list :");

        tblMembersList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Members ID", "Name", "Phone no"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMembersList);

        lblSalary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalary.setForeground(new java.awt.Color(0, 0, 153));
        lblSalary.setText("Salary :");

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSalary.addActionListener(this::txtSalaryActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMembersList)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMemberID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblEmployeeID))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblSalary)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDob)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblChooseType)
                                            .addComponent(lblPhone)
                                            .addComponent(lblFirstname)
                                            .addComponent(lblSurname))
                                        .addGap(0, 0, 0)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radioEmployee)
                                                .addGap(43, 43, 43)
                                                .addComponent(radioMember))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTeam)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblDepartment)
                                    .addGap(12, 12, 12)
                                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioStudent)
                                        .addGap(80, 80, 80)
                                        .addComponent(radioStaff))
                                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTrainer)
                                .addGap(18, 18, 18)
                                .addComponent(radioFemale)
                                .addGap(65, 65, 65)
                                .addComponent(radioMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnYes)
                                .addGap(88, 88, 88)
                                .addComponent(btnNo)
                                .addGap(97, 97, 97)
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCourse)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblPosition))
                                    .addComponent(lblType)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(76, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChooseType)
                    .addComponent(radioEmployee)
                    .addComponent(radioMember))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstname)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSurname)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(lblMemberID)
                    .addComponent(txtMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalary)
                    .addComponent(lblDob)
                    .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrainer)
                    .addComponent(lblGender)
                    .addComponent(radioMale)
                    .addComponent(radioFemale)
                    .addComponent(btnYes)
                    .addComponent(btnNo)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(24, 24, 24)
                .addComponent(lblMembersList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(radioStaff)
                    .addComponent(radioStudent))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPosition)
                    .addComponent(lblCourse)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(lblTeam)
                    .addComponent(txtDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMemberActionPerformed
        if(radioMember.isSelected()){
            lblFirstname.setVisible(true);
            txtFirstname.setVisible(true);
            lblSurname.setVisible(true);
            txtSurname.setVisible(true);
            lblFirstname.setVisible(true);
            txtFirstname.setVisible(true);
            lblSurname.setVisible(true);
            txtSurname.setVisible(true);
            lblGender.setVisible(true);
            radioMale.setVisible(true);
            radioFemale.setVisible(true);
            lblDob.setVisible(true);
            txtDob.setVisible(true);
            lblMemberID.setVisible(true);
            txtMemberID.setVisible(true);
            lblPhone.setVisible(true);
            txtPhone.setVisible(true);
            lblAddress.setVisible(true);
            txtAddress.setVisible(true);
            lblType.setVisible(true);
            radioStaff.setVisible(true);
            radioStudent.setVisible(true);
            lblSalary.setVisible(false);
            txtSalary.setVisible(false);
            lblEmployeeID.setVisible(false);
            txtEmployeeID.setVisible(false);
            lblTrainer.setVisible(false);
            btnYes.setVisible(false);
            btnNo.setVisible(false);
            lblMembersList.setVisible(false);
            tblMembersList.setVisible(false);
            tblMembersList.setVisible(false);
            jScrollPane1.setVisible(false);
            
            
            
            
        }else{
            lblFirstname.setVisible(false);
            txtFirstname.setVisible(false);
            lblSurname.setVisible(false);
            txtSurname.setVisible(false);
            lblGender.setVisible(false);
            radioMale.setVisible(false);
            radioFemale.setVisible(false);
            lblDob.setVisible(false);
            txtDob.setVisible(false);
            lblMemberID.setVisible(false);
            txtMemberID.setVisible(false);
            lblPhone.setVisible(false);
            txtPhone.setVisible(false);
            lblAddress.setVisible(false);
            txtAddress.setVisible(false);
            lblType.setVisible(false);
            radioStaff.setVisible(false);
            radioStudent.setVisible(false);
        }
    }//GEN-LAST:event_radioMemberActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void radioStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStaffActionPerformed
       if(radioStaff.isSelected()){
           lblPosition.setVisible(true);
           txtPosition.setVisible(true);
           lblDepartment.setVisible(true);
           txtDepartment.setVisible(true);
           lblCourse.setVisible(false);
           txtCourse.setVisible(false);
           lblTeam.setVisible(false);
           txtTeam.setVisible(false);
           
       }else{
           lblPosition.setVisible(false);
           txtPosition.setVisible(false);
           lblDepartment.setVisible(false);
           txtDepartment.setVisible(false);
       }
    }//GEN-LAST:event_radioStaffActionPerformed

    private void txtPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionActionPerformed

    private void radioStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStudentActionPerformed
        if(radioStudent.isSelected()){
           lblCourse.setVisible(true);
           txtCourse.setVisible(true);
           lblTeam.setVisible(true);
           txtTeam.setVisible(true);
           lblPosition.setVisible(false);
           txtPosition.setVisible(false);
           lblDepartment.setVisible(false);
           txtDepartment.setVisible(false);
           
        }else{
           lblCourse.setVisible(false);
           txtCourse.setVisible(false);
           lblTeam.setVisible(false);
           txtTeam.setVisible(false);
        }
    }//GEN-LAST:event_radioStudentActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartmentActionPerformed

    private void radioEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEmployeeActionPerformed
        if(radioEmployee.isSelected()){
            lblEmployeeID.setVisible(true);
            txtEmployeeID.setVisible(true);
            lblTrainer.setVisible(true);
            btnYes.setVisible(true);
            btnNo.setVisible(true);
            
            
            lblFirstname.setVisible(true);
            txtFirstname.setVisible(true);
            lblSurname.setVisible(true);
            txtSurname.setVisible(true);
            lblGender.setVisible(false);
            radioMale.setVisible(false);
            radioFemale.setVisible(false);
            lblDob.setVisible(false);
            txtDob.setVisible(false);
            lblMemberID.setVisible(false);
            txtMemberID.setVisible(false);
            lblPhone.setVisible(true);
            txtPhone.setVisible(true);
            lblAddress.setVisible(true);
            txtAddress.setVisible(true);
            lblSalary.setVisible(true);
            txtSalary.setVisible(true);
            lblType.setVisible(false);
            radioStaff.setVisible(false);
            radioStudent.setVisible(false);
            lblPosition.setVisible(false);
           txtPosition.setVisible(false);
           lblDepartment.setVisible(false);
           txtDepartment.setVisible(false);
           lblCourse.setVisible(false);
           txtCourse.setVisible(false);
           lblTeam.setVisible(false);
           txtTeam.setVisible(false);
           
           
            
        }else{
            lblEmployeeID.setVisible(false);
            txtEmployeeID.setVisible(false);
            lblTrainer.setVisible(false);
            btnYes.setVisible(false);
            btnNo.setVisible(false);
            lblSalary.setVisible(false);
            txtSalary.setVisible(false);
        }
    }//GEN-LAST:event_radioEmployeeActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseActionPerformed

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        if(btnYes.isSelected()){
            lblMembersList.setVisible(true);
            tblMembersList.setVisible(true);
            jScrollPane1.setVisible(true);
            
        }else{
            lblMembersList.setVisible(false);
            tblMembersList.setVisible(false);
            jScrollPane1.setVisible(false);
            
        }
    }//GEN-LAST:event_btnYesActionPerformed

    private void txtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        if(btnNo.isSelected()){
            lblMembersList.setVisible(false);
            tblMembersList.setVisible(false);
            jScrollPane1.setVisible(false);
            
        }
    }//GEN-LAST:event_btnNoActionPerformed

    private void txtMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMemberIDActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(radioMember.isSelected()){
        String firstName = txtFirstname.getText();
        String surname = txtSurname.getText();
        int MID = Integer.parseInt(txtMemberID.getText());
        int Phone = Integer.parseInt(txtPhone.getText());
        String address = txtAddress.getText();
        String dob = txtDob.getText();
        String gender = genderRadioGroup.getSelection().getActionCommand();
        
        if(radioStudent.isSelected()){
            String position = txtPosition.getText();
            String department = txtDepartment.getText();
        }else{
            String course = txtCourse.getText();
            String team = txtTeam.getText();
        }
        
        
        
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddPage().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private javax.swing.ButtonGroup chooseTypeRadioGroup;
    private javax.swing.ButtonGroup genderRadioGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblChooseType;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblMemberID;
    private javax.swing.JLabel lblMembersList;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JLabel lblTrainer;
    private javax.swing.JLabel lblType;
    private javax.swing.JRadioButton radioEmployee;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radioMember;
    private javax.swing.JRadioButton radioStaff;
    private javax.swing.JRadioButton radioStudent;
    private javax.swing.JTable tblMembersList;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtMemberID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtTeam;
    private javax.swing.ButtonGroup typeRadioGroup;
    private javax.swing.ButtonGroup yesOrNORadioGroup;
    // End of variables declaration//GEN-END:variables
}
