/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Main.*;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author marwa Purpose/Description: To allow the user to alter personal
 * information, for both employee and member.
 */
public class Alter extends javax.swing.JFrame {// check

    private Employee currentEmployee = null;
    private Member currentMember = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Alter.class.getName());

    /**
     * Creates new form AlterEmployee
     */
    public Alter() {
        initComponents();
        hideAllDisplaySection();
        hideEditSection();
        this.pack();
        buttonGroup1.add(memberRadio);
        buttonGroup1.add(empRadio);
        memberRadio.addActionListener(this::memberRadioActionPerformed);
        empRadio.addActionListener(this::empRadioActionPerformed);
        editbtn.addActionListener(this::editbtnActionPerformed);
        IDinput.addActionListener(this::IDinputActionPerformed);
        this.setResizable(false);
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        role = new javax.swing.JLabel();
        trainer = new javax.swing.JLabel();
        fnDisplay = new javax.swing.JLabel();
        snDisplay = new javax.swing.JLabel();
        addressDisplay = new javax.swing.JLabel();
        phoneAlter = new javax.swing.JLabel();
        salaryAlter = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        editbtn = new javax.swing.JButton();
        searchID = new javax.swing.JLabel();
        IDinput = new javax.swing.JTextField();
        fnAlter = new javax.swing.JLabel();
        fnInput = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        snAlter = new javax.swing.JLabel();
        salaryInput = new javax.swing.JTextField();
        phoneInput = new javax.swing.JTextField();
        addressAlter = new javax.swing.JLabel();
        phoneDisplay = new javax.swing.JLabel();
        salaryDisplay = new javax.swing.JLabel();
        SelectType = new javax.swing.JLabel();
        addressInput = new javax.swing.JTextField();
        snInput = new javax.swing.JTextField();
        empRadio = new javax.swing.JRadioButton();
        memberRadio = new javax.swing.JRadioButton();
        cancelbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        DOBDisplay = new javax.swing.JLabel();
        DOBAlter = new javax.swing.JLabel();
        DOBInput = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(214, 217, 223));

        role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        role.setForeground(new java.awt.Color(0, 0, 153));
        role.setText("Role :");

        trainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        trainer.setForeground(new java.awt.Color(0, 0, 153));
        trainer.setText("Trainer :");

        fnDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fnDisplay.setForeground(new java.awt.Color(0, 0, 153));
        fnDisplay.setText("First name :");

        snDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        snDisplay.setForeground(new java.awt.Color(0, 0, 153));
        snDisplay.setText("Surname :");

        addressDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addressDisplay.setForeground(new java.awt.Color(0, 0, 153));
        addressDisplay.setText("Address :");

        phoneAlter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phoneAlter.setForeground(new java.awt.Color(0, 0, 153));
        phoneAlter.setText("Phone no :");

        salaryAlter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salaryAlter.setForeground(new java.awt.Color(0, 0, 153));
        salaryAlter.setText("Salary :");

        editbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        editbtn.setForeground(new java.awt.Color(0, 0, 153));
        editbtn.setText("EDIT");
        editbtn.addActionListener(this::editbtnActionPerformed);

        searchID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchID.setForeground(new java.awt.Color(0, 0, 153));
        searchID.setText("Search ID :");

        IDinput.addActionListener(this::IDinputActionPerformed);

        fnAlter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fnAlter.setForeground(new java.awt.Color(0, 0, 153));
        fnAlter.setText("First name :");

        snAlter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        snAlter.setForeground(new java.awt.Color(0, 0, 153));
        snAlter.setText("Surname :");

        addressAlter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addressAlter.setForeground(new java.awt.Color(0, 0, 153));
        addressAlter.setText("Address :");

        phoneDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phoneDisplay.setForeground(new java.awt.Color(0, 0, 153));
        phoneDisplay.setText("Phone no :");

        salaryDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salaryDisplay.setForeground(new java.awt.Color(0, 0, 153));
        salaryDisplay.setText("Salary :");

        SelectType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SelectType.setForeground(new java.awt.Color(0, 0, 153));
        SelectType.setText("Select type to alter :");

        empRadio.setBackground(new java.awt.Color(214, 217, 223));
        empRadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        empRadio.setForeground(new java.awt.Color(0, 0, 153));
        empRadio.setText("Employee");
        empRadio.addActionListener(this::empRadioActionPerformed);

        memberRadio.setBackground(new java.awt.Color(214, 217, 223));
        memberRadio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        memberRadio.setForeground(new java.awt.Color(0, 0, 153));
        memberRadio.setText("Member");
        memberRadio.addActionListener(this::memberRadioActionPerformed);

        cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelbtn.setForeground(new java.awt.Color(0, 0, 153));
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(this::cancelbtnActionPerformed);

        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        savebtn.setForeground(new java.awt.Color(0, 0, 153));
        savebtn.setText("SAVE");
        savebtn.addActionListener(this::savebtnActionPerformed);

        DOBDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DOBDisplay.setForeground(new java.awt.Color(0, 0, 153));
        DOBDisplay.setText("DOB :");

        DOBAlter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DOBAlter.setForeground(new java.awt.Color(0, 0, 153));
        DOBAlter.setText("DOB :");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 153));
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(SelectType)
                .addGap(18, 18, 18)
                .addComponent(empRadio)
                .addGap(18, 18, 18)
                .addComponent(memberRadio))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(btnBack)
                .addGap(12, 12, 12)
                .addComponent(editbtn))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(fnAlter)
                .addGap(28, 28, 28)
                .addComponent(fnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(snAlter)
                .addGap(41, 41, 41)
                .addComponent(snInput, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(addressAlter)
                .addGap(49, 49, 49)
                .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(phoneAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(salaryAlter)
                .addGap(67, 67, 67)
                .addComponent(salaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(DOBAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(DOBInput, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(cancelbtn)
                .addGap(69, 69, 69)
                .addComponent(savebtn))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(fnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(snDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(addressDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(phoneDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(salaryDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(DOBDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(trainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searchID)
                        .addGap(98, 98, 98)
                        .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SelectType)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empRadio)
                            .addComponent(memberRadio))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchID)
                    .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(role)
                    .addComponent(trainer))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(fnDisplay)
                .addGap(6, 6, 6)
                .addComponent(snDisplay)
                .addGap(6, 6, 6)
                .addComponent(addressDisplay)
                .addGap(12, 12, 12)
                .addComponent(phoneDisplay)
                .addGap(6, 6, 6)
                .addComponent(salaryDisplay)
                .addGap(12, 12, 12)
                .addComponent(DOBDisplay)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(editbtn))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(fnAlter))
                    .addComponent(fnInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(snAlter))
                    .addComponent(snInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(addressAlter))
                    .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(phoneAlter))
                    .addComponent(phoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(salaryAlter))
                    .addComponent(salaryInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(DOBAlter))
                    .addComponent(DOBInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelbtn)
                    .addComponent(savebtn)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//This part is responsible for handling the display, depending if employee or member is chosen
    private void empRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRadioActionPerformed
        if (empRadio.isSelected()) {
            hideEditSection();
            hideAllDisplaySection();
            showEmpDisplaySection();
            IDinput.setText("");
            this.pack();
        }
    }//GEN-LAST:event_empRadioActionPerformed

    private void memberRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberRadioActionPerformed
        if (memberRadio.isSelected()) {
            hideEditSection();
            hideAllDisplaySection();
            showMemberDisplaySection();
            IDinput.setText("");
            this.pack();
        }
    }//GEN-LAST:event_memberRadioActionPerformed
    //Upon clicking edit button, it checks if the textbox for search ID is empty or invalid, and if not it displays info to alter.
    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        String id = IDinput.getText().trim();

        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an ID first.");
            return;
        }
        if (empRadio.isSelected() && currentEmployee == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please search and find a valid employee first.");
            return;
        }
        if (memberRadio.isSelected() && currentMember == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please search and find a valid member first.");
            return;
        }

        if (empRadio.isSelected()) {
            fnInput.setText(currentEmployee.getName());
            snInput.setText("");
            addressInput.setText(currentEmployee.getAddress() != null ? currentEmployee.getAddress() : "");
            phoneInput.setText(String.valueOf(currentEmployee.getPhoneNumber()));
            salaryInput.setText(String.valueOf(currentEmployee.getSalary()));
            showEmpEditSection();
        } else if (memberRadio.isSelected()) {
            fnInput.setText(currentMember.getName());
            snInput.setText("");
            addressInput.setText(currentMember.getAddress() != null ? currentMember.getAddress() : "");
            phoneInput.setText(String.valueOf(currentMember.getPhoneNumber()));
            DOBInput.setText(currentMember.getDOB() != null ? currentMember.getDOB() : "");
            showMemberEditSection();
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void IDinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDinputActionPerformed
        if (empRadio.isSelected()) {
            searchEmployee();
        } else if (memberRadio.isSelected()) {
            searchMember();
        }
    }
//Controls what variables are displayed and what aren't

    private void hideAllDisplaySection() {
        role.setVisible(false);
        trainer.setVisible(false);
        fnDisplay.setVisible(false);
        snDisplay.setVisible(false);
        addressDisplay.setVisible(false);
        phoneDisplay.setVisible(false);
        salaryDisplay.setVisible(false);
        DOBDisplay.setVisible(false);
        jSeparator1.setVisible(false);
        editbtn.setVisible(false);
        jSeparator2.setVisible(false);
        searchID.setVisible(false);
        IDinput.setVisible(false);
    }

    private void showEmpDisplaySection() {
        searchID.setVisible(true);
        IDinput.setVisible(true);
        role.setVisible(true);
        trainer.setVisible(true);
        fnDisplay.setVisible(true);
        snDisplay.setVisible(true);
        addressDisplay.setVisible(true);
        phoneDisplay.setVisible(true);
        salaryDisplay.setVisible(true);
        DOBDisplay.setVisible(false);
        jSeparator1.setVisible(true);
        editbtn.setVisible(true);
        jSeparator2.setVisible(true);
    }

    private void showMemberDisplaySection() {
        searchID.setVisible(true);
        IDinput.setVisible(true);
        role.setVisible(true);
        trainer.setVisible(false);
        fnDisplay.setVisible(true);
        snDisplay.setVisible(true);
        addressDisplay.setVisible(true);
        phoneDisplay.setVisible(true);
        salaryDisplay.setVisible(false);
        DOBDisplay.setVisible(true);
        jSeparator1.setVisible(true);
        editbtn.setVisible(true);
        jSeparator2.setVisible(true);
    }

    private void hideEditSection() {
        fnAlter.setVisible(false);
        fnInput.setVisible(false);
        snAlter.setVisible(false);
        snInput.setVisible(false);
        addressAlter.setVisible(false);
        addressInput.setVisible(false);
        phoneAlter.setVisible(false);
        phoneInput.setVisible(false);
        salaryAlter.setVisible(false);
        salaryInput.setVisible(false);
        DOBAlter.setVisible(false);
        DOBInput.setVisible(false);
        savebtn.setVisible(false);
        cancelbtn.setVisible(false);
    }

    private void showEmpEditSection() {
        fnAlter.setVisible(true);
        fnInput.setVisible(true);
        snAlter.setVisible(true);
        snInput.setVisible(true);
        addressAlter.setVisible(true);
        addressInput.setVisible(true);
        phoneAlter.setVisible(true);
        phoneInput.setVisible(true);
        salaryAlter.setVisible(true);
        salaryInput.setVisible(true);
        DOBAlter.setVisible(false);
        DOBInput.setVisible(false);
        savebtn.setVisible(true);
        cancelbtn.setVisible(true);
    }

    private void showMemberEditSection() {
        fnAlter.setVisible(true);
        fnInput.setVisible(true);
        snAlter.setVisible(true);
        snInput.setVisible(true);
        addressAlter.setVisible(true);
        addressInput.setVisible(true);
        phoneAlter.setVisible(true);
        phoneInput.setVisible(true);
        salaryAlter.setVisible(false);
        salaryInput.setVisible(false);
        DOBAlter.setVisible(true);
        DOBInput.setVisible(true);
        savebtn.setVisible(true);
        cancelbtn.setVisible(true);
    }

    //Displays information for either employee or member when an ID is entered
    private void searchEmployee() {
        String id = IDinput.getText().trim();
        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an ID.");
            return;
        }

        currentEmployee = null;

        for (Users u : StoreUsers.users) {
            if (String.valueOf(u.userID).equals(id) && u instanceof Employee) {
                currentEmployee = (Employee) u;
                break;
            }
        }

        if (currentEmployee == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No employee found with ID: " + id);
            role.setText("Role :");
            trainer.setText("Trainer :");
            fnDisplay.setText("First name :");
            snDisplay.setText("Surname :");
            addressDisplay.setText("Address :");
            phoneDisplay.setText("Phone no :");
            salaryDisplay.setText("Salary :");
            hideEditSection();
            return;
        }

        role.setText("Role :  Employee");

        if (currentEmployee instanceof Trainer t) {
            trainer.setText("Trainer :  Yes");
            salaryDisplay.setText("Salary :  " + t.getSalary());
        } else {
            trainer.setText("Trainer :  No");
            salaryDisplay.setText("Salary :  " + currentEmployee.getSalary());
        }

        String fullName = currentEmployee.getName().trim();
        int seperator = fullName.indexOf(" ");

        String fN;
        String sN;

        if (seperator != -1) {
            fN = fullName.substring(0, seperator);
            sN = fullName.substring(seperator + 1);
        } else {
            fN = fullName;
            sN = "";
        }

        fnDisplay.setText("First name :  " + fN);
        snDisplay.setText("Surname :  " + sN);
        addressDisplay.setText("Address :  " + currentEmployee.getAddress());
        phoneDisplay.setText("Phone no :  " + currentEmployee.getPhoneNumber());
        hideEditSection();

    }

    private void searchMember() {
        String id = IDinput.getText().trim();
        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an ID.");
            return;
        }

        currentMember = null;

        for (Users u : StoreUsers.users) {
            if (String.valueOf(u.userID).equals(id) && u instanceof Member) {
                currentMember = (Member) u;
                break;
            }
        }

        if (currentMember == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No member found with ID: " + id);
            role.setText("Role :");
            fnDisplay.setText("First name :");
            snDisplay.setText("Surname :");
            addressDisplay.setText("Address :");
            phoneDisplay.setText("Phone no :");
            DOBDisplay.setText("DOB :");
            hideEditSection();
            return;
        }
        String fullName = currentMember.getName().trim();
        int separator = fullName.indexOf(" ");
        String fN = separator != -1 ? fullName.substring(0, separator) : fullName;
        String sN = separator != -1 ? fullName.substring(separator + 1) : "";

        role.setText("Role :  Member");
        fnDisplay.setText("First name :  " + fN);
        snDisplay.setText("Surname :  " + sN);
        addressDisplay.setText("Address :  " + currentMember.getAddress());
        phoneDisplay.setText("Phone no :  " + currentMember.getPhoneNumber());
        DOBDisplay.setText("DOB :  " + currentMember.getDOB());
        hideEditSection();
    }//GEN-LAST:event_IDinputActionPerformed
//Hides the section shown for altering 
    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        hideEditSection();
        this.pack();
    }//GEN-LAST:event_cancelbtnActionPerformed
//Saves the altered information user entered
    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if (empRadio.isSelected()) {
            if (fnInput.getText().trim().isEmpty()
                    || snInput.getText().trim().isEmpty()
                    || addressInput.getText().trim().isEmpty()
                    || phoneInput.getText().trim().isEmpty()
                    || salaryInput.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields before saving.");
                return;
            }
            try {
                currentEmployee.setName(fnInput.getText().trim());
                currentEmployee.setAddress(addressInput.getText().trim());
                currentEmployee.setPhoneNumber(Integer.parseInt(phoneInput.getText().trim()));
                currentEmployee.setSalary(Double.parseDouble(salaryInput.getText().trim()));
                StoreUsers.save();
                searchEmployee();
                hideEditSection();
                javax.swing.JOptionPane.showMessageDialog(this, "Employee updated successfully.");
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Phone and salary must be valid numbers.");
            }

        } else if (memberRadio.isSelected()) {
            if (fnInput.getText().trim().isEmpty()
                    || snInput.getText().trim().isEmpty()
                    || addressInput.getText().trim().isEmpty()
                    || phoneInput.getText().trim().isEmpty()
                    || DOBInput.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields before saving.");
                return;
            }
            try {
                currentMember.setName(fnInput.getText().trim());
                currentMember.setAddress(addressInput.getText().trim());
                currentMember.setPhoneNumber(Integer.parseInt(phoneInput.getText().trim()));
                currentMember.setDOB(DOBInput.getText().trim());
                StoreUsers.save();
                searchMember();
                hideEditSection();
                javax.swing.JOptionPane.showMessageDialog(this, "Member updated successfully.");
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Phone number must be a valid number.");
            }
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();

        //to close the page without exiting the whole program
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        StoreUsers.loadStartupFile();

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Alter().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOBAlter;
    private javax.swing.JLabel DOBDisplay;
    private javax.swing.JTextField DOBInput;
    private javax.swing.JTextField IDinput;
    private javax.swing.JLabel SelectType;
    private javax.swing.JLabel addressAlter;
    private javax.swing.JLabel addressDisplay;
    private javax.swing.JTextField addressInput;
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JRadioButton empRadio;
    private javax.swing.JLabel fnAlter;
    private javax.swing.JLabel fnDisplay;
    private javax.swing.JTextField fnInput;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton memberRadio;
    private javax.swing.JLabel phoneAlter;
    private javax.swing.JLabel phoneDisplay;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel role;
    private javax.swing.JLabel salaryAlter;
    private javax.swing.JLabel salaryDisplay;
    private javax.swing.JTextField salaryInput;
    private javax.swing.JButton savebtn;
    private javax.swing.JLabel searchID;
    private javax.swing.JLabel snAlter;
    private javax.swing.JLabel snDisplay;
    private javax.swing.JTextField snInput;
    private javax.swing.JLabel trainer;
    // End of variables declaration//GEN-END:variables
}
