/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Main.Trainer;
import Main.Users;
import Main.Member;
import Main.StoreUsers;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marwa
 */
public class List extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(List.class.getName());

    /**
     * Creates new form List
     */
    public List() {
        initComponents();
        this.pack();
        buttonGroup1.add(memberRadio);
        buttonGroup1.add(empRadio);

        memberRadio.addActionListener(this::memberRadioActionPerformed);
        empRadio.addActionListener(this::empRadioActionPerformed);
        MemberTable.getTableHeader().setBackground(new java.awt.Color(0, 0, 153));
        MemberTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        MemberTable.setBackground(java.awt.Color.WHITE);
        MemberTable.setForeground(new java.awt.Color(0, 0, 153));

        TrainerTable.getTableHeader().setBackground(new java.awt.Color(0, 0, 153));
        TrainerTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        TrainerTable.setBackground(java.awt.Color.WHITE);
        TrainerTable.setForeground(new java.awt.Color(0, 0, 153));

        ((DefaultTableModel) MemberTable.getModel()).setRowCount(0);
        ((DefaultTableModel) TrainerTable.getModel()).setRowCount(0);

        hideMembersSection();
        hideTrainersSection();

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Trainerselection = new javax.swing.JLabel();
        Trainer = new javax.swing.JLabel();
        TrainerIDTop = new javax.swing.JLabel();
        NameTop = new javax.swing.JLabel();
        PhoneTop = new javax.swing.JLabel();
        Membersassigned = new javax.swing.JLabel();
        PersonalInfo = new javax.swing.JLabel();
        TrainerIDAssigned = new javax.swing.JLabel();
        PhoneAssigned = new javax.swing.JLabel();
        MemberInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemberTable = new javax.swing.JTable();
        TotalMembersAssigned = new javax.swing.JLabel();
        Printbtn = new javax.swing.JButton();
        NameAssigned = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        TrainerCombobox = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        empRadio = new javax.swing.JRadioButton();
        memberRadio = new javax.swing.JRadioButton();
        TrainerInfo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TrainerTable = new javax.swing.JTable();
        memberInput = new javax.swing.JLabel();
        memberComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(214, 217, 223));

        Trainerselection.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Trainerselection.setForeground(new java.awt.Color(0, 0, 153));
        Trainerselection.setText("Select list type :");

        Trainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Trainer.setForeground(new java.awt.Color(0, 0, 153));
        Trainer.setText("Trainer :");

        TrainerIDTop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TrainerIDTop.setForeground(new java.awt.Color(0, 0, 153));
        TrainerIDTop.setText("Trainer ID :");

        NameTop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NameTop.setForeground(new java.awt.Color(0, 0, 153));
        NameTop.setText("Name :");

        PhoneTop.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneTop.setForeground(new java.awt.Color(0, 0, 153));
        PhoneTop.setText("Phone :");

        Membersassigned.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Membersassigned.setForeground(new java.awt.Color(0, 0, 153));
        Membersassigned.setText("Members assigned to trainer :");

        PersonalInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PersonalInfo.setForeground(new java.awt.Color(0, 0, 153));
        PersonalInfo.setText("Personal trainer information :");

        TrainerIDAssigned.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TrainerIDAssigned.setForeground(new java.awt.Color(0, 0, 153));
        TrainerIDAssigned.setText("Trainer ID :");

        PhoneAssigned.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneAssigned.setForeground(new java.awt.Color(0, 0, 153));
        PhoneAssigned.setText("Phone :");

        MemberInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MemberInfo.setForeground(new java.awt.Color(0, 0, 153));
        MemberInfo.setText("Member information :");

        MemberTable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        MemberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Member ID", "Name", "Phone"
            }
        ));
        jScrollPane1.setViewportView(MemberTable);

        TotalMembersAssigned.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TotalMembersAssigned.setForeground(new java.awt.Color(0, 0, 153));
        TotalMembersAssigned.setText("Total members assigned :");

        Printbtn.setBackground(new java.awt.Color(0, 0, 153));
        Printbtn.setForeground(new java.awt.Color(255, 255, 255));
        Printbtn.setText("Print list");
        Printbtn.addActionListener(this::PrintbtnActionPerformed);

        NameAssigned.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NameAssigned.setForeground(new java.awt.Color(0, 0, 153));
        NameAssigned.setText("Name :");

        TrainerCombobox.addActionListener(this::TrainerComboboxActionPerformed);

        empRadio.setBackground(new java.awt.Color(214, 217, 223));
        empRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        empRadio.setForeground(new java.awt.Color(0, 0, 153));
        empRadio.setText("Trainer");
        empRadio.addActionListener(this::empRadioActionPerformed);

        memberRadio.setBackground(new java.awt.Color(214, 217, 223));
        memberRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        memberRadio.setForeground(new java.awt.Color(0, 0, 153));
        memberRadio.setText("Member");
        memberRadio.addActionListener(this::memberRadioActionPerformed);

        TrainerInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TrainerInfo.setForeground(new java.awt.Color(0, 0, 153));
        TrainerInfo.setText("Trainer information :");

        TrainerTable.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        TrainerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Trainer ID", "Name", "Phone"
            }
        ));
        jScrollPane3.setViewportView(TrainerTable);

        memberInput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        memberInput.setForeground(new java.awt.Color(0, 0, 153));
        memberInput.setText("Member :");

        memberComboBox.addActionListener(this::memberComboBoxActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(Membersassigned))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(PersonalInfo))
            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(MemberInfo)
                .addGap(56, 56, 56)
                .addComponent(TrainerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(TotalMembersAssigned))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(Printbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Trainerselection)
                .addGap(73, 73, 73)
                .addComponent(empRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(memberRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrainerIDTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(memberInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Trainer, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TrainerCombobox, 0, 138, Short.MAX_VALUE)
                            .addComponent(memberComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(NameTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhoneTop, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TrainerIDAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(PhoneAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(NameAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Trainerselection)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(empRadio)
                                    .addComponent(memberRadio))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Trainer)
                            .addComponent(TrainerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(memberInput))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(memberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TrainerIDTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhoneTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Membersassigned)
                .addGap(6, 6, 6)
                .addComponent(PersonalInfo)
                .addGap(6, 6, 6)
                .addComponent(TrainerIDAssigned)
                .addGap(6, 6, 6)
                .addComponent(NameAssigned)
                .addGap(12, 12, 12)
                .addComponent(PhoneAssigned)
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MemberInfo)
                    .addComponent(TrainerInfo))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(TotalMembersAssigned)
                .addGap(40, 40, 40)
                .addComponent(Printbtn)
                .addGap(94, 94, 94)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        String selected = (String) TrainerCombobox.getSelectedItem();

        if (selected == null || selected.equals("Select a Trainer") || selected.equals("No trainers found")) {
            JOptionPane.showMessageDialog(this, "Please select a trainer before printing.");
            return;
        }

        try {
            MemberTable.print();
        } catch (java.awt.print.PrinterException ex) {
            JOptionPane.showMessageDialog(this, "Printing the list has failed: " + ex.getMessage());
        }
    }//GEN-LAST:event_PrintbtnActionPerformed

    private void TrainerComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerComboboxActionPerformed
        if (loading) {
            return;
        }
        String selected = (String) TrainerCombobox.getSelectedItem();

        if (selected == null || selected.equals("Select a Trainer") || selected.equals("No trainers found")) {
            clearDisplay();
            return;
        }

        int selectedID = Integer.parseInt(selected.split(" ")[0].trim());
        for (Users u : StoreUsers.users) {
            if (u.userID == selectedID && u instanceof Trainer t) {
                displayTrainerInfo(t);
                loadAssignedMembers(t);
                break;
            }
        }

    }//GEN-LAST:event_TrainerComboboxActionPerformed

    private void empRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRadioActionPerformed
        if (empRadio.isSelected()) {
            hideMembersSection();
            showTrainersSection();
        }
    }//GEN-LAST:event_empRadioActionPerformed

    private void memberRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberRadioActionPerformed
        if (memberRadio.isSelected()) {
            hideTrainersSection();
            showMembersSection();
        }
    }//GEN-LAST:event_memberRadioActionPerformed

    private void memberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberComboBoxActionPerformed
        String selected = (String) memberComboBox.getSelectedItem();
        if (selected == null || selected.equals("Select a Member")) {
            return;
        }

        int selectedID = Integer.parseInt(selected.split(" ")[0].trim());

        for (Users u : StoreUsers.users) {
            if (u.userID == selectedID && u instanceof Member m) {
                TrainerIDTop.setText("Member ID : " + m.userID);
                NameTop.setText("Name : " + m.getName());
                PhoneTop.setText("Phone : " + m.getPhoneNumber());

                for (Users t : StoreUsers.users) {
                    if (t instanceof Trainer trainer) {
                        for (Member assigned : trainer.getAssignedMembers()) {
                            if (assigned.userID == m.userID) {
                                TrainerIDAssigned.setText("Trainer ID : " + trainer.userID);
                                NameAssigned.setText("Name : " + trainer.getName());
                                PhoneAssigned.setText("Phone : " + trainer.getPhoneNumber());
                                loadAssignedMembers(trainer);
                                break;
                            }
                        }
                    }
                }
                break;
            }
        }
    }//GEN-LAST:event_memberComboBoxActionPerformed

    private void hideMembersSection() {
        memberInput.setVisible(false);
        memberComboBox.setVisible(false);
        Trainer.setVisible(false);
        TrainerCombobox.setVisible(false);
        TrainerIDTop.setVisible(false);
        NameTop.setVisible(false);
        PhoneTop.setVisible(false);
        jSeparator1.setVisible(false);
        Membersassigned.setVisible(false);
        PersonalInfo.setVisible(false);
        TrainerIDAssigned.setVisible(false);
        NameAssigned.setVisible(false);
        PhoneAssigned.setVisible(false);
        jSeparator2.setVisible(false);
        MemberInfo.setVisible(false);
        jScrollPane1.setVisible(false);
        jSeparator4.setVisible(false);
        TotalMembersAssigned.setVisible(false);
        Printbtn.setVisible(false);
    }

    private void showMembersSection() {
        memberInput.setVisible(true);
        memberComboBox.setVisible(true);
        NameTop.setVisible(true);
        PhoneTop.setVisible(true);
        jSeparator1.setVisible(true);
        Membersassigned.setVisible(true);
        PersonalInfo.setVisible(true);
        TrainerIDAssigned.setVisible(true);
        NameAssigned.setVisible(true);
        PhoneAssigned.setVisible(true);
        jSeparator2.setVisible(true);
        MemberInfo.setVisible(true);
        jScrollPane1.setVisible(true);
        jSeparator4.setVisible(true);
        TotalMembersAssigned.setVisible(true);
        Printbtn.setVisible(true);
        loadMembers();
    }

    private void hideTrainersSection() {
        memberInput.setVisible(false);
        memberComboBox.setVisible(false);
        Trainer.setVisible(false);
        TrainerCombobox.setVisible(false);
        TrainerIDTop.setVisible(false);
        NameTop.setVisible(false);
        PhoneTop.setVisible(false);
        jScrollPane3.setVisible(false);
        TrainerInfo.setVisible(false);
        Printbtn.setVisible(false);
    }

    private void showTrainersSection() {
        Trainer.setVisible(true);
        TrainerCombobox.setVisible(true);
        TrainerIDTop.setVisible(true);
        NameTop.setVisible(true);
        PhoneTop.setVisible(true);
        jScrollPane3.setVisible(true);
        TrainerInfo.setVisible(true);
        Printbtn.setVisible(true);
        loadAllTrainers();
    }
    private boolean loading = false;
    private void loadAllTrainers() {
        loading = true;
        TrainerCombobox.removeAllItems();
        TrainerCombobox.addItem("Select a Trainer");

        if (StoreUsers.users == null || StoreUsers.users.isEmpty()) {
            TrainerCombobox.addItem("No trainers found");
            return;
        }
        for (Users u : StoreUsers.users) {
            if (u instanceof Trainer t) {
                TrainerCombobox.addItem(t.userID + " " + t.getName());
            }
        }
        DefaultTableModel model = (DefaultTableModel) TrainerTable.getModel();
        model.setRowCount(0);

        ArrayList<Users> users = StoreUsers.users;

        for (int i = 0; i < users.size(); i++) {
            Users u = users.get(i);
            if (u instanceof Trainer t) {
                model.addRow(new Object[]{
                    t.userID,
                    t.getName(),
                    String.valueOf(t.getPhoneNumber())
                });
            }
        }
        loading = false;
    }

     private void loadMembers() {
        memberComboBox.removeAllItems();
        memberComboBox.addItem("Select a Member");

        for (Users u : StoreUsers.users) {
            if (u instanceof Member m) {
                memberComboBox.addItem(m.userID + " " + m.getName());
            }
        }
    }
     

    private void displayTrainerInfo(Trainer trainer) {
        // Section 1 of page (select trainer)
        TrainerIDTop.setText("Trainer ID : " + trainer.userID);
        NameTop.setText("Name : " + trainer.getName());
        PhoneTop.setText("Phone : " + trainer.getPhoneNumber());

        // Section 2 of page (members assigned to trainer)
        TrainerIDAssigned.setText("Trainer ID : " + trainer.userID);
        NameAssigned.setText("Name : " + trainer.getName());
        PhoneAssigned.setText("Phone : " + trainer.getPhoneNumber());
    }

    private void loadAssignedMembers(Trainer trainer) {
        DefaultTableModel model = (DefaultTableModel) MemberTable.getModel();
        model.setRowCount(0);

        ArrayList<Member> members = trainer.getAssignedMembers();

        for (int i = 0; i < members.size(); i++) {
            Member m = members.get(i);
            model.addRow(new Object[]{
                m.userID,
                m.getName(),
                String.valueOf(m.getPhoneNumber())
            });
        }

        TotalMembersAssigned.setText("Total Members Assigned : " + members.size());
    }

    private void clearDisplay() {
        TrainerIDTop.setText("Trainer ID :");
        NameTop.setText("Name :");
        PhoneTop.setText("Phone :");

        TrainerIDAssigned.setText("Trainer ID :");
        NameAssigned.setText("Name :");
        PhoneAssigned.setText("Phone :");

        DefaultTableModel model = (DefaultTableModel) MemberTable.getModel();
        model.setRowCount(0);

        TotalMembersAssigned.setText("Total Members Assigned :");
    }

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        StoreUsers.loadStartupFile();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName()); // same as TrainerManage
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new List().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MemberInfo;
    private javax.swing.JTable MemberTable;
    private javax.swing.JLabel Membersassigned;
    private javax.swing.JLabel NameAssigned;
    private javax.swing.JLabel NameTop;
    private javax.swing.JLabel PersonalInfo;
    private javax.swing.JLabel PhoneAssigned;
    private javax.swing.JLabel PhoneTop;
    private javax.swing.JButton Printbtn;
    private javax.swing.JLabel TotalMembersAssigned;
    private javax.swing.JLabel Trainer;
    private javax.swing.JComboBox<String> TrainerCombobox;
    private javax.swing.JLabel TrainerIDAssigned;
    private javax.swing.JLabel TrainerIDTop;
    private javax.swing.JLabel TrainerInfo;
    private javax.swing.JTable TrainerTable;
    private javax.swing.JLabel Trainerselection;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton empRadio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> memberComboBox;
    private javax.swing.JLabel memberInput;
    private javax.swing.JRadioButton memberRadio;
    // End of variables declaration//GEN-END:variables
}
