/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Main.*;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Remove extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Remove.class.getName());
    private Employee currentEmployee = null;
    private Member currentMember = null;

    /**
     * Creates new form Remove
     */
    public Remove() {
        initComponents();
        this.pack();
        buttonGroup1.add(memberRadio);
        buttonGroup1.add(employeeRadio);
        memberRadio.addActionListener(this::memberRadioActionPerformed);
        employeeRadio.addActionListener(this::employeeRadioActionPerformed);
        DefaultTableModel model = (DefaultTableModel) Memberslist.getModel();
        model.setRowCount(0);
        Memberslist.getTableHeader().setForeground(new java.awt.Color(0, 0, 153));
        Memberslist.setForeground(new java.awt.Color(0, 0, 153));
        hideEmployeeSection();
        hideMemberSection();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Role = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        PhoneNum = new javax.swing.JLabel();
        Trainer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Memberslist = new javax.swing.JTable();
        removeMemberBtn = new javax.swing.JButton();
        Removebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        trainerLbl = new javax.swing.JLabel();
        firstNameLbl = new javax.swing.JLabel();
        phoneNumLbl = new javax.swing.JLabel();
        AssignedTrainer = new javax.swing.JLabel();
        TrainerID = new javax.swing.JLabel();
        memberRadio = new javax.swing.JRadioButton();
        employeeRadio = new javax.swing.JRadioButton();
        SelectType = new javax.swing.JLabel();
        SearchID = new javax.swing.JLabel();
        IDinput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(214, 217, 223));

        Role.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Role.setForeground(new java.awt.Color(0, 0, 153));
        Role.setText("Role :");

        FirstName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FirstName.setForeground(new java.awt.Color(0, 0, 153));
        FirstName.setText("First Name :");

        Surname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Surname.setForeground(new java.awt.Color(0, 0, 153));
        Surname.setText("Surname :");

        PhoneNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PhoneNum.setForeground(new java.awt.Color(0, 0, 153));
        PhoneNum.setText("Phone no :");

        Trainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Trainer.setForeground(new java.awt.Color(0, 0, 153));
        Trainer.setText("Trainer :");

        Memberslist.setForeground(new java.awt.Color(0, 102, 153));
        Memberslist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Member ID", "Name", "Phone No"
            }
        ));
        jScrollPane1.setViewportView(Memberslist);

        removeMemberBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeMemberBtn.setForeground(new java.awt.Color(0, 0, 153));
        removeMemberBtn.setText("Remove members list");
        removeMemberBtn.addActionListener(this::removeMemberBtnActionPerformed);

        Removebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Removebtn.setForeground(new java.awt.Color(0, 0, 153));
        Removebtn.setText("Remove");
        Removebtn.addActionListener(this::RemovebtnActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Members List :");

        AssignedTrainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AssignedTrainer.setForeground(new java.awt.Color(0, 0, 153));
        AssignedTrainer.setText("Assigned Trainer :");

        TrainerID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TrainerID.setForeground(new java.awt.Color(0, 0, 153));
        TrainerID.setText("Trainer ID :");

        memberRadio.setBackground(new java.awt.Color(214, 217, 223));
        memberRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        memberRadio.setForeground(new java.awt.Color(0, 0, 153));
        memberRadio.setText("Member");
        memberRadio.addActionListener(this::memberRadioActionPerformed);

        employeeRadio.setBackground(new java.awt.Color(214, 217, 223));
        employeeRadio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeRadio.setForeground(new java.awt.Color(0, 0, 153));
        employeeRadio.setText("Employee");
        employeeRadio.addActionListener(this::employeeRadioActionPerformed);

        SelectType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SelectType.setForeground(new java.awt.Color(0, 0, 153));
        SelectType.setText("Select type to remove : ");

        SearchID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SearchID.setForeground(new java.awt.Color(0, 0, 153));
        SearchID.setText("Search ID :");

        IDinput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IDinput.addActionListener(this::IDinputActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(phoneNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(firstNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Role)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Trainer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(trainerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(SelectType)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(employeeRadio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(memberRadio))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(SearchID)
                                        .addGap(32, 32, 32)
                                        .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeMemberBtn)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssignedTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrainerID, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Removebtn)
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectType)
                    .addComponent(employeeRadio)
                    .addComponent(memberRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDinput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Trainer)
                            .addComponent(Role))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FirstName)
                .addGap(2, 2, 2)
                .addComponent(Surname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNum, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AssignedTrainer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrainerID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(phoneNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeMemberBtn)
                .addGap(18, 18, 18)
                .addComponent(Removebtn)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMemberBtnActionPerformed
        if (currentEmployee == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please search for a trainer first.");
            return;
        }

        if (!(currentEmployee instanceof Trainer t)) {
            javax.swing.JOptionPane.showMessageDialog(this, "This employee is not a trainer.");
            return;
        }

        if (t.getAssignedMembers().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "There are no members assigned to this trainer.");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to remove all the members?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            t.getAssignedMembers().clear();
            StoreUsers.save();
            ((DefaultTableModel) Memberslist.getModel()).setRowCount(0);
            javax.swing.JOptionPane.showMessageDialog(this, "Members removed successfully!");
        }
    }//GEN-LAST:event_removeMemberBtnActionPerformed

    private void RemovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovebtnActionPerformed
        if (memberRadio.isSelected()) {
            if (currentMember == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please search for a member first.");
                return;
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to remove this member?", "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                Trainer t = (Trainer) currentMember.getAssignedTrainer();
                if (t != null) {
                    t.getAssignedMembers().remove(currentMember);
                }

                StoreUsers.users.remove(currentMember);
                StoreUsers.save();
                currentMember = null;

                IDinput.setText("");
                firstNameLbl.setText("");
                phoneNumLbl.setText("");

                javax.swing.JOptionPane.showMessageDialog(this, "Member removed successfully!");
            }

        } else if (employeeRadio.isSelected()) {
            if (currentEmployee == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please search for an employee first.");
                return;
            }

            if (currentEmployee instanceof Trainer t) {
                if (!t.getAssignedMembers().isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Cannot remove this employee, the members are still assigned.",
                            "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to remove this employee?",
                    "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                StoreUsers.users.remove(currentEmployee);
                StoreUsers.save();
                currentEmployee = null;

                IDinput.setText("");
                trainerLbl.setText("");
                firstNameLbl.setText("");
                phoneNumLbl.setText("");
                ((DefaultTableModel) Memberslist.getModel()).setRowCount(0);

                javax.swing.JOptionPane.showMessageDialog(this, "Employee removed successfully!");
            }

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a type first (Trainer or Member).");
        }
    }//GEN-LAST:event_RemovebtnActionPerformed

    private void IDinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDinputActionPerformed
        if (employeeRadio.isSelected()) {
            searchEmployee();
        } else if (memberRadio.isSelected()) {
            searchMember();
        }
    }//GEN-LAST:event_IDinputActionPerformed

    private void searchEmployee() {
        String id = IDinput.getText().trim();
        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an ID.");
            return;
        }

        currentEmployee = null;

        for (Users u : StoreUsers.users) {
            if (String.valueOf(u.userID).equals(id) && u instanceof Employee) {
                currentEmployee = (Employee) u;
                break;
            }
        }

        if (currentEmployee == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No employee found with ID: " + id);
            Role.setText("Role :");
            Trainer.setText("Trainer :");
            FirstName.setText("First Name :");
            Surname.setText("Surname :");
            PhoneNum.setText("Phone no :");
            ((DefaultTableModel) Memberslist.getModel()).setRowCount(0);
            return;
        }

        String fullName = currentEmployee.getName().trim();
        int separator = fullName.indexOf(" ");
        String fN = separator != -1 ? fullName.substring(0, separator) : fullName;
        String sN = separator != -1 ? fullName.substring(separator + 1) : "";

        Role.setText("Role :  Employee");
        FirstName.setText("First Name :  " + fN);
        Surname.setText("Surname :  " + sN);
        PhoneNum.setText("Phone no :  " + currentEmployee.getPhoneNumber());

        if (currentEmployee instanceof Trainer t) {
            Trainer.setText("Trainer :  Yes");
            DefaultTableModel model = (DefaultTableModel) Memberslist.getModel();
            model.setRowCount(0);
            for (Member m : t.getAssignedMembers()) {
                model.addRow(new Object[]{m.userID, m.getName(), String.valueOf(m.getPhoneNumber())});
            }
        } else {
            Trainer.setText("Trainer :  No");
            ((DefaultTableModel) Memberslist.getModel()).setRowCount(0);
        }
    }

    private void searchMember() {
        String id = IDinput.getText().trim();
        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an ID.");
            return;
        }

        currentMember = null;

        for (Users u : StoreUsers.users) {
            if (String.valueOf(u.userID).equals(id) && u instanceof Member) {
                currentMember = (Member) u;
                break;
            }
        }

        if (currentMember == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No member found with ID: " + id);
            Role.setText("Role :");
            FirstName.setText("First Name :");
            Surname.setText("Surname :");
            PhoneNum.setText("Phone no :");
            AssignedTrainer.setText("Assigned Trainer :");
            TrainerID.setText("Trainer ID :");
            return;
        }

        String fullName = currentMember.getName().trim();
        int separator = fullName.indexOf(" ");
        String fN = separator != -1 ? fullName.substring(0, separator) : fullName;
        String sN = separator != -1 ? fullName.substring(separator + 1) : "";

        Role.setText("Role :  Member");
        FirstName.setText("First Name :  " + fN);
        Surname.setText("Surname :  " + sN);
        PhoneNum.setText("Phone no :  " + currentMember.getPhoneNumber());

        Trainer t = (Trainer) currentMember.getAssignedTrainer();
        if (t != null) {
            AssignedTrainer.setText("Assigned Trainer :  " + t.getName());
            TrainerID.setText("Trainer ID :  " + t.userID);
        } else {
            AssignedTrainer.setText("Assigned Trainer : None");
            TrainerID.setText("Trainer ID : No ID found");
        }
    }

    private void hideEmployeeSection() {
        SearchID.setVisible(false);
        IDinput.setVisible(false);
        Role.setVisible(false);
        Trainer.setVisible(false);
        trainerLbl.setVisible(false);
        FirstName.setVisible(false);
        firstNameLbl.setVisible(false);
        Surname.setVisible(false);
        PhoneNum.setVisible(false);
        phoneNumLbl.setVisible(false);
        jLabel3.setVisible(false);
        jScrollPane1.setVisible(false);
        removeMemberBtn.setVisible(false);
        Removebtn.setVisible(false);
        AssignedTrainer.setVisible(false);
        TrainerID.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(false);
    }

    private void showEmployeeSection() {
        SearchID.setVisible(true);
        IDinput.setVisible(true);
        Role.setVisible(true);
        Trainer.setVisible(true);
        trainerLbl.setVisible(true);
        FirstName.setVisible(true);
        firstNameLbl.setVisible(true);
        Surname.setVisible(true);
        PhoneNum.setVisible(true);
        phoneNumLbl.setVisible(true);
        jLabel3.setVisible(true);
        jScrollPane1.setVisible(true);
        removeMemberBtn.setVisible(true);
        Removebtn.setVisible(true);
        jSeparator1.setVisible(true);
        jSeparator2.setVisible(true);
    }

    private void hideMemberSection() {
        SearchID.setVisible(false);
        IDinput.setVisible(false);
        Role.setVisible(false);
        FirstName.setVisible(false);
        firstNameLbl.setVisible(false);
        Surname.setVisible(false);
        PhoneNum.setVisible(false);
        phoneNumLbl.setVisible(false);
        AssignedTrainer.setVisible(false);
        TrainerID.setVisible(false);
        Removebtn.setVisible(false);
        Trainer.setVisible(false);
        trainerLbl.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(false);
        jLabel3.setVisible(false);
        jScrollPane1.setVisible(false);
        removeMemberBtn.setVisible(false);
    }

    private void showMemberSection() {
        SearchID.setVisible(true);
        IDinput.setVisible(true);
        Role.setVisible(true);
        FirstName.setVisible(true);
        firstNameLbl.setVisible(true);
        Surname.setVisible(true);
        PhoneNum.setVisible(true);
        phoneNumLbl.setVisible(true);
        AssignedTrainer.setVisible(true);
        jSeparator1.setVisible(true);
        jSeparator2.setVisible(true);
        TrainerID.setVisible(true);
        Removebtn.setVisible(true);
    }

    private void employeeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRadioActionPerformed
        if (employeeRadio.isSelected()) {
            hideMemberSection();
            showEmployeeSection();
            IDinput.setText("");
            this.pack();
        }
    }//GEN-LAST:event_employeeRadioActionPerformed

    private void memberRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberRadioActionPerformed
        if (memberRadio.isSelected()) {
            hideEmployeeSection();
            showMemberSection();
            IDinput.setText("");
            this.pack();
        }
    }//GEN-LAST:event_memberRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        StoreUsers.loadStartupFile();
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Remove().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AssignedTrainer;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField IDinput;
    private javax.swing.JTable Memberslist;
    private javax.swing.JLabel PhoneNum;
    private javax.swing.JButton Removebtn;
    private javax.swing.JLabel Role;
    private javax.swing.JLabel SearchID;
    private javax.swing.JLabel SelectType;
    private javax.swing.JLabel Surname;
    private javax.swing.JLabel Trainer;
    private javax.swing.JLabel TrainerID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton employeeRadio;
    private javax.swing.JLabel firstNameLbl;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton memberRadio;
    private javax.swing.JLabel phoneNumLbl;
    private javax.swing.JButton removeMemberBtn;
    private javax.swing.JLabel trainerLbl;
    // End of variables declaration//GEN-END:variables
}
