/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Main.*;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class TrainerManage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrainerManage.class.getName());

    /**
     * Creates new form TrainerManage
     */
    public TrainerManage() {
        initComponents();

        MemberTable.getTableHeader().setBackground(new java.awt.Color(0, 0, 153));
        MemberTable.getTableHeader().setForeground(java.awt.Color.WHITE);
        MemberTable.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 13));
        MemberTable.setBackground(java.awt.Color.WHITE);
        MemberTable.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) MemberTable.getModel();
        model.setRowCount(0);

        loadTrainers();
        loadUnassignedMembers();

        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrainerManagePanel = new javax.swing.JPanel();
        SelectTrainer = new javax.swing.JLabel();
        Trainerinput = new javax.swing.JLabel();
        Assigning = new javax.swing.JLabel();
        Select = new javax.swing.JLabel();
        Assigning1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemberTable = new javax.swing.JTable();
        AssignMemberBtn = new javax.swing.JButton();
        RemoveMemberBtn = new javax.swing.JButton();
        RemoveTrainerAssignedBtn = new javax.swing.JButton();
        RemoveMemberPanel = new javax.swing.JPanel();
        RemoveMember = new javax.swing.JLabel();
        RemoveCombobox = new javax.swing.JComboBox<>();
        MemberCombobox = new javax.swing.JComboBox<>();
        TrainerCombobox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TrainerManagePanel.setBackground(new java.awt.Color(214, 217, 223));

        SelectTrainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SelectTrainer.setForeground(new java.awt.Color(0, 0, 153));
        SelectTrainer.setText("Select trainer :");

        Trainerinput.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Trainerinput.setForeground(new java.awt.Color(0, 0, 153));
        Trainerinput.setText("Trainer :");

        Assigning.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Assigning.setForeground(new java.awt.Color(0, 0, 153));
        Assigning.setText("Assign member to trainer :");

        Select.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Select.setForeground(new java.awt.Color(0, 0, 153));
        Select.setText("Select member :");

        Assigning1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Assigning1.setForeground(new java.awt.Color(0, 0, 153));
        Assigning1.setText("Assigned members :");

        MemberTable.setForeground(new java.awt.Color(31, 58, 117));
        MemberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Member ID", "Name", "Phone No"
            }
        ));
        MemberTable.setGridColor(new java.awt.Color(242, 242, 242));
        MemberTable.setSelectionBackground(new java.awt.Color(0, 0, 153));
        jScrollPane1.setViewportView(MemberTable);

        AssignMemberBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AssignMemberBtn.setForeground(new java.awt.Color(0, 0, 153));
        AssignMemberBtn.setText("Assign Member");
        AssignMemberBtn.addActionListener(this::AssignMemberBtnActionPerformed);

        RemoveMemberBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RemoveMemberBtn.setForeground(new java.awt.Color(0, 0, 153));
        RemoveMemberBtn.setText("Remove Member");
        RemoveMemberBtn.addActionListener(this::RemoveMemberBtnActionPerformed);

        RemoveTrainerAssignedBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        RemoveTrainerAssignedBtn.setForeground(new java.awt.Color(0, 0, 153));
        RemoveTrainerAssignedBtn.setText("Remove Member from trainer");
        RemoveTrainerAssignedBtn.addActionListener(this::RemoveTrainerAssignedBtnActionPerformed);

        RemoveMemberPanel.setBackground(new java.awt.Color(214, 217, 223));
        RemoveMemberPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        RemoveMember.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RemoveMember.setForeground(new java.awt.Color(0, 0, 153));
        RemoveMember.setText("Remove member from trainer :");

        RemoveCombobox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RemoveCombobox.addActionListener(this::RemoveComboboxActionPerformed);

        javax.swing.GroupLayout RemoveMemberPanelLayout = new javax.swing.GroupLayout(RemoveMemberPanel);
        RemoveMemberPanel.setLayout(RemoveMemberPanelLayout);
        RemoveMemberPanelLayout.setHorizontalGroup(
            RemoveMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveMemberPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(RemoveMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveMember)
                    .addComponent(RemoveCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        RemoveMemberPanelLayout.setVerticalGroup(
            RemoveMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RemoveMemberPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(RemoveMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        MemberCombobox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MemberCombobox.addActionListener(this::MemberComboboxActionPerformed);

        TrainerCombobox.addActionListener(this::TrainerComboboxActionPerformed);

        javax.swing.GroupLayout TrainerManagePanelLayout = new javax.swing.GroupLayout(TrainerManagePanel);
        TrainerManagePanel.setLayout(TrainerManagePanelLayout);
        TrainerManagePanelLayout.setHorizontalGroup(
            TrainerManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainerManagePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(TrainerManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RemoveMemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TrainerManagePanelLayout.createSequentialGroup()
                        .addGroup(TrainerManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TrainerManagePanelLayout.createSequentialGroup()
                                .addComponent(Trainerinput)
                                .addGap(18, 18, 18)
                                .addComponent(TrainerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SelectTrainer)
                            .addComponent(Assigning)
                            .addComponent(Select)
                            .addComponent(MemberCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Assigning1))
                        .addGap(268, 268, 268))
                    .addGroup(TrainerManagePanelLayout.createSequentialGroup()
                        .addGroup(TrainerManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RemoveMemberBtn)
                            .addComponent(AssignMemberBtn))
                        .addGap(11, 11, 11)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TrainerManagePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemoveTrainerAssignedBtn)
                .addGap(24, 24, 24))
        );
        TrainerManagePanelLayout.setVerticalGroup(
            TrainerManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrainerManagePanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(SelectTrainer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrainerManagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Trainerinput)
                    .addComponent(TrainerCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Assigning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Select)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(AssignMemberBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Assigning1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(RemoveMemberBtn)
                .addGap(18, 18, 18)
                .addComponent(RemoveMemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RemoveTrainerAssignedBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrainerManagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TrainerManagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrainerComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerComboboxActionPerformed
        String trainerSelected = (String) TrainerCombobox.getSelectedItem();

        if (trainerSelected == null || trainerSelected.equals("Select a Trainer") || trainerSelected.equals("No trainers found")) {
            DefaultTableModel model = (DefaultTableModel) MemberTable.getModel();
            model.setRowCount(0);
            RemoveCombobox.removeAllItems();
            return;
        }

        int selectedID = Integer.parseInt(trainerSelected.split(" ")[0].trim());

        ArrayList<Users> users = StoreUsers.users;

        for (int i = 0; i < users.size(); i++) {
            Users u = users.get(i);
            if (u.userID == selectedID && u instanceof Trainer) {
                Trainer selectedTrainer = (Trainer) u;
                loadAssignedMembers(selectedTrainer);
                break;
            }
        }
    }//GEN-LAST:event_TrainerComboboxActionPerformed

    private void MemberComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberComboboxActionPerformed

    private void RemoveComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoveComboboxActionPerformed

    private void RemoveTrainerAssignedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTrainerAssignedBtnActionPerformed
        String trainerSelected = (String) TrainerCombobox.getSelectedItem();
        String memberSelected = (String) RemoveCombobox.getSelectedItem();

        if (trainerSelected == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a trainer.");
            return;
        }

        if (memberSelected == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a member to remove.");
            return;
        }

        String trainerId = trainerSelected.split(" - ")[0].trim();
        String memberId = memberSelected.split(" - ")[0].trim();

        Trainer selectedTrainer = null;

        java.util.ArrayList<Users> users = StoreUsers.users;

        for (int i = 0; i < users.size(); i++) {
            Users u = users.get(i);
            if (String.valueOf(u.userID).equalsIgnoreCase(trainerId) && u instanceof Trainer) {
                selectedTrainer = (Trainer) u;
                break;
            }
        }

        if (selectedTrainer == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Trainer not found.");
            return;
        }

        Member toRemove = null;

        java.util.ArrayList<Member> members = selectedTrainer.getAssignedMembers();

        for (int i = 0; i < members.size(); i++) {
            Member m = members.get(i);
            if (String.valueOf(m.userID).equals(memberId)) {
                toRemove = m;
                break;
            }
        }

        if (toRemove == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Member not found.");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to remove this member from the trainer?",
                "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            selectedTrainer.getAssignedMembers().remove(toRemove);
            StoreUsers.save();

            RemoveCombobox.removeItem(memberSelected);

            DefaultTableModel model = (DefaultTableModel) MemberTable.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).toString().equals(memberId)) {
                    model.removeRow(i);
                    break;
                }
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Member removed from trainer successfully!");
            loadUnassignedMembers();
        }
    }//GEN-LAST:event_RemoveTrainerAssignedBtnActionPerformed

    private void RemoveMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveMemberBtnActionPerformed
        String trainerSelected = (String) TrainerCombobox.getSelectedItem();

        if (trainerSelected == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a trainer.");
            return;
        }

        int selectedRow = MemberTable.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a member from the table.");
            return;
        }

        String trainerId = trainerSelected.split(" - ")[0].trim();
        Trainer selectedTrainer = null;

        java.util.ArrayList<Users> users = StoreUsers.users;

        for (int i = 0; i < users.size(); i++) {
            Users u = users.get(i);
            if (String.valueOf(u.userID).equalsIgnoreCase(trainerId) && u instanceof Trainer) {
                selectedTrainer = (Trainer) u;
                break;
            }
        }

        if (selectedTrainer == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Trainer not found.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) MemberTable.getModel();
        String memberId = model.getValueAt(selectedRow, 0).toString();

        Member toRemove = null;

        java.util.ArrayList<Member> members = selectedTrainer.getAssignedMembers();

        for (int i = 0; i < members.size(); i++) {
            Member m = members.get(i);
            if (String.valueOf(m.userID).equals(memberId)) {
                toRemove = m;
                break;
            }
        }

        if (toRemove == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Member not found.");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to remove this member?",
                "Confirm", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            selectedTrainer.getAssignedMembers().remove(toRemove);
            StoreUsers.save();

            model.removeRow(selectedRow);
            RemoveCombobox.removeItem(toRemove.userID + " - " + toRemove.getName());

            javax.swing.JOptionPane.showMessageDialog(this, "Member removed successfully!");
            loadUnassignedMembers();
        }
    }//GEN-LAST:event_RemoveMemberBtnActionPerformed

    private void AssignMemberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignMemberBtnActionPerformed
        String trainerSelected = (String) TrainerCombobox.getSelectedItem();
        String memberSelected = (String) MemberCombobox.getSelectedItem();

        if (trainerSelected == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a trainer.");
            return;
        }

        if (memberSelected == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a member.");
            return;
        }

        String trainerId = trainerSelected.split(" - ")[0].trim();
        String memberId = memberSelected.split(" - ")[0].trim();

        Trainer selectedTrainer = null;
        Member selectedMember = null;

        ArrayList<Users> users = StoreUsers.users;

        for (int i = 0; i < users.size(); i++) {
            Users u = users.get(i);
            if (String.valueOf(u.userID).equalsIgnoreCase(trainerId) && u instanceof Trainer) {
                selectedTrainer = (Trainer) u;
            }
            if (String.valueOf(u.userID).equalsIgnoreCase(memberId) && u instanceof Member) {
                selectedMember = (Member) u;
            }
        }

        if (selectedTrainer == null || selectedMember == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Could not find trainer or member.");
            return;
        }

        selectedTrainer.getAssignedMembers().add(selectedMember);
        StoreUsers.save();

        javax.swing.JOptionPane.showMessageDialog(this, "Member assigned successfully!");
        loadAssignedMembers(selectedTrainer);
        loadUnassignedMembers();
    }//GEN-LAST:event_AssignMemberBtnActionPerformed

    private void loadTrainers() {
        TrainerCombobox.removeAllItems();
        TrainerCombobox.addItem("Select a Trainer");

        if (StoreUsers.users == null || StoreUsers.users.isEmpty()) {
            TrainerCombobox.addItem("No trainers found");
            return;
        }

        ArrayList<Users> users = StoreUsers.users;

        for (int i = 0; i < users.size(); i++) {
            Users u = users.get(i);
            if (u instanceof Trainer) {
                TrainerCombobox.addItem(u.userID + " " + u.getName());
            }
        }
    }

    private void loadUnassignedMembers() {
        MemberCombobox.removeAllItems();
        MemberCombobox.addItem("Select a Member to assign");

        ArrayList<Users> users = StoreUsers.users;

        boolean anyUnassigned = false;

        for (int i = 0; i < users.size(); i++) {
            Users u = users.get(i);
            if (u instanceof Member m) {
                boolean isAssigned = false;

                for (int j = 0; j < users.size(); j++) {
                    Users u2 = users.get(j);
                    if (u2 instanceof Trainer t && t.getAssignedMembers().contains(m)) {
                        isAssigned = true;
                        break;
                    } else {
                    }
                }

                if (!isAssigned) {
                    MemberCombobox.addItem(m.userID + " - " + m.getName());
                    anyUnassigned = true;
                }
            }
        }
        if (!anyUnassigned) {
            MemberCombobox.addItem("No members found");
        }
    }

    private void loadAssignedMembers(Trainer trainer) {
        DefaultTableModel model = (DefaultTableModel) MemberTable.getModel();
        model.setRowCount(0);
        RemoveCombobox.removeAllItems();
        RemoveCombobox.addItem("Select a Member to remove");

        ArrayList<Member> members = trainer.getAssignedMembers();

        for (int i = 0; i < members.size(); i++) {
            Member m = members.get(i);
            model.addRow(new Object[]{
                m.userID,
                m.getName(),
                String.valueOf(m.getPhoneNumber())
            });
            RemoveCombobox.addItem(m.userID + " - " + m.getName());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrainerManage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignMemberBtn;
    private javax.swing.JLabel Assigning;
    private javax.swing.JLabel Assigning1;
    private javax.swing.JComboBox<String> MemberCombobox;
    private javax.swing.JTable MemberTable;
    private javax.swing.JComboBox<String> RemoveCombobox;
    private javax.swing.JLabel RemoveMember;
    private javax.swing.JButton RemoveMemberBtn;
    private javax.swing.JPanel RemoveMemberPanel;
    private javax.swing.JButton RemoveTrainerAssignedBtn;
    private javax.swing.JLabel Select;
    private javax.swing.JLabel SelectTrainer;
    private javax.swing.JComboBox<String> TrainerCombobox;
    private javax.swing.JPanel TrainerManagePanel;
    private javax.swing.JLabel Trainerinput;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
